### ISSUE TITLE
Seems Interesting...

### ISSUE THREAD

**Issue by TylerGames** [LostTeam/LostBackup#1]
How will this actually work?

**Comment by MCUnderground** [comment]
It will backup worlds probably to another folder idk. Jason is good developer so ofc it seems interesting

**Comment by jasonwynn10** [comment]
thanks MC
this plugin will work by copying the current worlds folder to the plugins data folder
then it will be renamed to the date and time it is saved

**Comment by jasonwynn10** [comment]
there will also be an automatic part of it

**Comment by jasonwynn10** [comment]
also, I'm seriously surprised that no one has thought of doing this

**Comment by remotevase** [comment]
@jasonwynn10 well, people have, but its not a very good title. This is the most appropriate title

**Comment by MCUnderground** [comment]
You mean by lost backup? Lol

**Comment by jasonwynn10** [comment]
I found a plugin for the old version of PocketMine. It was a pmf file

**Comment by remotevase** [comment]
theres another one thats a phar but its still outdated
